// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: byte/v/forge/contracts/proxyruntime/v1/proxy_runtime.proto

/* eslint-disable */

export const protobufPackage = "byte.v.forge.contracts.proxyruntime.v1";

export enum ProxyProtocol {
  PROXY_PROTOCOL_UNSPECIFIED = "PROXY_PROTOCOL_UNSPECIFIED",
  PROXY_PROTOCOL_HTTP = "PROXY_PROTOCOL_HTTP",
  PROXY_PROTOCOL_SOCKS5 = "PROXY_PROTOCOL_SOCKS5",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyProvider {
  PROXY_PROVIDER_UNSPECIFIED = "PROXY_PROVIDER_UNSPECIFIED",
  PROXY_PROVIDER_STATIC = "PROXY_PROVIDER_STATIC",
  PROXY_PROVIDER_1024PROXY = "PROXY_PROVIDER_1024PROXY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyCapability {
  PROXY_CAPABILITY_UNSPECIFIED = "PROXY_CAPABILITY_UNSPECIFIED",
  PROXY_CAPABILITY_CHAINING = "PROXY_CAPABILITY_CHAINING",
  PROXY_CAPABILITY_POOL_REFRESH = "PROXY_CAPABILITY_POOL_REFRESH",
  PROXY_CAPABILITY_API_POOL = "PROXY_CAPABILITY_API_POOL",
  PROXY_CAPABILITY_STICKY_SESSION = "PROXY_CAPABILITY_STICKY_SESSION",
  PROXY_CAPABILITY_ACTIVE_SESSION_ROTATION = "PROXY_CAPABILITY_ACTIVE_SESSION_ROTATION",
  PROXY_CAPABILITY_USERNAME_PARAMETER_SESSION = "PROXY_CAPABILITY_USERNAME_PARAMETER_SESSION",
  PROXY_CAPABILITY_UNIFIED_EGRESS_GATEWAY = "PROXY_CAPABILITY_UNIFIED_EGRESS_GATEWAY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxySessionMode {
  PROXY_SESSION_MODE_UNSPECIFIED = "PROXY_SESSION_MODE_UNSPECIFIED",
  PROXY_SESSION_MODE_ROTATING = "PROXY_SESSION_MODE_ROTATING",
  PROXY_SESSION_MODE_STICKY = "PROXY_SESSION_MODE_STICKY",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyUpstreamKind {
  PROXY_UPSTREAM_KIND_UNSPECIFIED = "PROXY_UPSTREAM_KIND_UNSPECIFIED",
  PROXY_UPSTREAM_KIND_SIMPLE_PROXY = "PROXY_UPSTREAM_KIND_SIMPLE_PROXY",
  PROXY_UPSTREAM_KIND_DYNAMIC_IP = "PROXY_UPSTREAM_KIND_DYNAMIC_IP",
  PROXY_UPSTREAM_KIND_PROXY_POOL = "PROXY_UPSTREAM_KIND_PROXY_POOL",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxyRotationMode {
  PROXY_ROTATION_MODE_UNSPECIFIED = "PROXY_ROTATION_MODE_UNSPECIFIED",
  PROXY_ROTATION_MODE_NONE = "PROXY_ROTATION_MODE_NONE",
  PROXY_ROTATION_MODE_PER_REQUEST = "PROXY_ROTATION_MODE_PER_REQUEST",
  PROXY_ROTATION_MODE_STICKY_SESSION = "PROXY_ROTATION_MODE_STICKY_SESSION",
  PROXY_ROTATION_MODE_SCHEDULED_POOL_REFRESH = "PROXY_ROTATION_MODE_SCHEDULED_POOL_REFRESH",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum ProxySelectorStrategy {
  PROXY_SELECTOR_STRATEGY_UNSPECIFIED = "PROXY_SELECTOR_STRATEGY_UNSPECIFIED",
  PROXY_SELECTOR_STRATEGY_ROUND_ROBIN = "PROXY_SELECTOR_STRATEGY_ROUND_ROBIN",
  PROXY_SELECTOR_STRATEGY_RANDOM = "PROXY_SELECTOR_STRATEGY_RANDOM",
  PROXY_SELECTOR_STRATEGY_FIFO = "PROXY_SELECTOR_STRATEGY_FIFO",
  PROXY_SELECTOR_STRATEGY_HASH_CLIENT_IP = "PROXY_SELECTOR_STRATEGY_HASH_CLIENT_IP",
  PROXY_SELECTOR_STRATEGY_HASH_TARGET_HOST = "PROXY_SELECTOR_STRATEGY_HASH_TARGET_HOST",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum EgressHopRole {
  EGRESS_HOP_ROLE_UNSPECIFIED = "EGRESS_HOP_ROLE_UNSPECIFIED",
  EGRESS_HOP_ROLE_FORWARD = "EGRESS_HOP_ROLE_FORWARD",
  EGRESS_HOP_ROLE_EXIT = "EGRESS_HOP_ROLE_EXIT",
  EGRESS_HOP_ROLE_CONTROL_PLANE = "EGRESS_HOP_ROLE_CONTROL_PLANE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export enum EgressListenerKind {
  EGRESS_LISTENER_KIND_UNSPECIFIED = "EGRESS_LISTENER_KIND_UNSPECIFIED",
  EGRESS_LISTENER_KIND_DIRECT = "EGRESS_LISTENER_KIND_DIRECT",
  EGRESS_LISTENER_KIND_PROVIDER_ROUTE = "EGRESS_LISTENER_KIND_PROVIDER_ROUTE",
  UNRECOGNIZED = "UNRECOGNIZED",
}

export interface ProxySelectorPolicy {
  strategy: ProxySelectorStrategy;
  max_fails: number;
  fail_timeout: string;
}

export interface ProxyProviderDescriptor {
  provider_id: string;
  provider: ProxyProvider;
  display_name: string;
  capabilities: ProxyCapability[];
  protocols: ProxyProtocol[];
  supports_active_new_session: boolean;
  min_sticky_ttl_minutes: number;
  max_sticky_ttl_minutes: number;
  upstream_kinds: ProxyUpstreamKind[];
  rotation_modes: ProxyRotationMode[];
}

export interface ProviderControlPlaneAccess {
  uses_proxy: boolean;
  proxy_ref: string;
  protocols: ProxyProtocol[];
}

export interface ProxySessionPolicy {
  mode: ProxySessionMode;
  region: string;
  state: string;
  city: string;
  asn: string;
  sticky_ttl_minutes: number;
  labels: { [key: string]: string };
  upstream_kind: ProxyUpstreamKind;
  rotation_mode: ProxyRotationMode;
}

export interface ProxySessionPolicy_LabelsEntry {
  key: string;
  value: string;
}

export interface ProxySession {
  session_id: string;
  provider: ProxyProvider;
  policy: ProxySessionPolicy | undefined;
  created_at: string | undefined;
  expires_at: string | undefined;
  labels: { [key: string]: string };
}

export interface ProxySession_LabelsEntry {
  key: string;
  value: string;
}

export interface ProxyEndpoint {
  id: string;
  provider: ProxyProvider;
  protocol: ProxyProtocol;
  host: string;
  port: number;
  session_id: string;
  upstream_kind: ProxyUpstreamKind;
  rotation_mode: ProxyRotationMode;
  labels: { [key: string]: string };
}

export interface ProxyEndpoint_LabelsEntry {
  key: string;
  value: string;
}

export interface ProxyPoolSnapshot {
  pool_id: string;
  provider: ProxyProviderDescriptor | undefined;
  active_session: ProxySession | undefined;
  endpoints: ProxyEndpoint[];
  refreshed_at: string | undefined;
}

export interface EgressListener {
  listener_id: string;
  kind: EgressListenerKind;
  listen_addr: string;
  protocol: ProxyProtocol;
  route_id: string;
  managed: boolean;
  labels: { [key: string]: string };
}

export interface EgressListener_LabelsEntry {
  key: string;
  value: string;
}

export interface EgressHop {
  hop_id: string;
  order: number;
  role: EgressHopRole;
  selector: ProxySelectorPolicy | undefined;
  endpoints: ProxyEndpoint[];
}

export interface EgressRoute {
  route_id: string;
  hops: EgressHop[];
}

export interface EgressGateway {
  gateway_id: string;
  listeners: EgressListener[];
  pool: ProxyPoolSnapshot | undefined;
  data_plane_route: EgressRoute | undefined;
  control_plane_route: EgressRoute | undefined;
  provider_control_plane: ProviderControlPlaneAccess | undefined;
  updated_at: string | undefined;
}

export interface ListProxyProvidersRequest {
}

export interface ListProxyProvidersResponse {
  providers: ProxyProviderDescriptor[];
}

export interface GetEgressGatewayRequest {
  gateway_id: string;
}

export interface GetEgressGatewayResponse {
  gateway: EgressGateway | undefined;
}

export interface GetProxyPoolRequest {
  pool_id: string;
}

export interface GetProxyPoolResponse {
  pool: ProxyPoolSnapshot | undefined;
}

export interface RefreshProxyPoolRequest {
  pool_id: string;
}

export interface RefreshProxyPoolResponse {
  pool: ProxyPoolSnapshot | undefined;
}

export interface CreateProxySessionRequest {
  pool_id: string;
  provider_id: string;
  policy: ProxySessionPolicy | undefined;
  force_new: boolean;
}

export interface CreateProxySessionResponse {
  session: ProxySession | undefined;
  pool: ProxyPoolSnapshot | undefined;
}

export interface ListEgressListenersRequest {
  gateway_id: string;
}

export interface ListEgressListenersResponse {
  listeners: EgressListener[];
}

export interface CreateEgressListenerRequest {
  gateway_id: string;
  listener_id: string;
  listen_addr: string;
  protocol: ProxyProtocol;
  kind: EgressListenerKind;
  labels: { [key: string]: string };
}

export interface CreateEgressListenerRequest_LabelsEntry {
  key: string;
  value: string;
}

export interface CreateEgressListenerResponse {
  listener: EgressListener | undefined;
  gateway: EgressGateway | undefined;
}
